In [1]:
import torch

# Tensors
PyTorch en su esencia es una libreria para procesar tensors. Un tensor puede ser un numero, un vector, una matriz o cual arreglo n-dimensional.

In [2]:
# Numero
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is una forma abreviada de escribir `4.0`. Se utiliza para indicarle a Pytorch que queremos crear un numero punto flotante. Se puede verificar el tipo de un tensor.

In [3]:
t1.dtype

torch.float32

Como se mencionaba previamente, un tensor no es unicamente un numero. Puede ser un vector, una matriz o cualquier tipo de arreglo n-dimensional. Veamos 3 ejemplos.

In [4]:
# Vector
t2 = torch.tensor([1. , 2, 3 , 4])
t2

tensor([1., 2., 3., 4.])

Es interesante notar que Pytorch puede generalizar los tipos de un tensor. En este caso, solamente se declara que el `1.` es un numero punto flotante, no obstante convierte los restantes numeros del tensor a punto flotante.

In [5]:
# Matriz
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# Arreglo de 3 dimensiones
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Como se puede ver los tensores pueden tener multiples dimensiones y diferentes tamaños en cada dimension. Pytorch por defecto trae un método que nos permite ver el tamaño de un tensor.

In [7]:
print(f'Tamano de un Tensor de un numero {t1.shape}.')
print(f'Tamano de un Tensor de un Vector {t2.shape}.')
print(f'Tamano de un Tensor de una Matriz {t3.shape}.')
print(f'Tamano de un Tensor de un arreglo de 3 dimensiones {t4.shape}.')

Tamano de un Tensor de un numero torch.Size([]).
Tamano de un Tensor de un Vector torch.Size([4]).
Tamano de un Tensor de una Matriz torch.Size([3, 2]).
Tamano de un Tensor de un arreglo de 3 dimensiones torch.Size([2, 2, 3]).


# Operaciones con tensores y gradientes
Se pueden aplicar las propiedades aritmeticas basicas a los tensores. Veamos unos ejemplos:

In [8]:
# Se definen 3 tensores basicos
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [9]:
# Operacion aritmetica basica
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

Como era esperado `y` es un tensor con el valor de `3 * 4 + 5 = 17`. Lo que hace a Pytorch especial es que automaticamente calcula la derivada de `y` con respecto a los tensores que tienen `requires_grad` seteado como `True`. Para calcular las derivadas podemos llamar al metodo `.backward` en el tensor de resultado y.

In [10]:
# Se calculan las derivadas
y.backward()

Las derivadas de `y` con respecto a los tensores de entrada son guardados en el atributo `.grad` de los respectivos tensores de entrada.

In [11]:
# Se muestran los gradientes
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# Interoperabilidad con Numpy

Numpy es una de las librerias mas populares para el calculo matematico y cientifico en Python. Pytorch trabaja con una filosofia de interoperabilidad por sobre reinventar la rueda, por lo cual puede comunicarse realmente bien en la mayoria de las funciones con Numpy.

Por ejemplo, asi es como se crea una matriz en Numpy.

In [12]:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

La cual puede ser convertida a un tensor de Pytorch simplemente utilizando el metodo `torch.from_numpy`

In [13]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

El traspaso de los tipos de datos funciona perfectamente

In [14]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

De igual forma podemos convertir un tensor a un arreglo de Numpy utilizando el metodo `.numpy`.

In [15]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])